// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsptU3GVvXaP-OAaZjoa50G3vLL_OwWpw',
    appId: '1:666896413630:android:f458d701d4223e5d843fef',
    messagingSenderId: '666896413630',
    projectId: 'konsultasi-c1330',
    databaseURL: 'https://konsultasi-c1330-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'konsultasi-c1330.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFkTyrWYjRZPrrgYSJsz_B5-VlSO57aBU',
    appId: '1:666896413630:ios:bec29fe1d8816b64843fef',
    messagingSenderId: '666896413630',
    projectId: 'konsultasi-c1330',
    databaseURL: 'https://konsultasi-c1330-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'konsultasi-c1330.appspot.com',
    iosBundleId: 'com.example.konsul',
  );
}
